#!/bin/bash

# Put this script in /usr/local/bin/ and make sure this path is part of bash
# environment ($PATH). Then it can be run anywhere as long as the current
# directory is a git repository.
#
# For each author, this script displays:
#   - insertions
#   - deletions
#   - files
#   - commits
# and the total count.
#
# Prerequisite: `awk'

if [[ $# -ne 0 ]]
then
   echo "Usage: $0"
   exit 1
fi

git log --numstat | awk '
function printStats(author) {
  printf "\033[4m%s:\n\033[0m", author

  printf "  [+] insertions: %d  (%.0f%%)\n",
    more[author], (more[author] / more["total"] * 100)

  printf "  [-] deletions: %d  (%.0f%%)\n",
    less[author], (less[author] / less["total"] * 100)

  printf "  files: %d  (%.0f%%)\n",
    file[author], (file[author] / file["total"] * 100)

  printf "  commits: %d  (%.0f%%)\n",
    commits[author], (commits[author] / commits["total"] * 100)
}

/^Author:/ {
  author           = $2 " " $3
  commits[author]  += 1
  commits["total"] += 1
}

/^[0-9]/ {
  more[author] += $1
  less[author] += $2
  file[author] += 1

  more["total"] += $1
  less["total"] += $2
  file["total"] += 1
}

END {
  for (author in commits) {
    if (author != "total") {
      printStats(author)
    }
  }
  printStats("total")
}'
